window.BDO_DATA = {
  quests: [
    {id:'ravikel-test', name:"[Daily] Ravikel's Test", reset:'Daily', npc:'Ravikel', location:"Oquilla's Eye Wharf", region:"Oquilla's Eye", priority:'S+', solo:'Solo', ship:'Caravel+', difficulty:'Medium', time:'10-20 min', objective:'Defeat the requested sea monsters for Ravikel. Pick the version that matches your current ship strength.', bestReward:'Ship upgrade material bundle / rare sea material', why:'Directly supports Carrack materials and keeps your sailing routine efficient.', stage:'Do now with Caravel'},
    {id:'young-candidum', name:"[Daily] Old Moon Guild's Young Candidum Hunter", reset:'Daily', npc:'Ravikel', location:"Oquilla's Eye", region:"Great Ocean", priority:'S+', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', time:'15 min', objective:'Defeat Young Candidum and return to Ravikel.', bestReward:'Moon Scale Plywood / rare sea material option', why:'Core Carrack path material source. Continue after Carrack for gear progress.', stage:'Do now with Caravel'},
    {id:'young-nineshark', name:"[Daily] Old Moon Guild's Young Nineshark Hunter", reset:'Daily', npc:'Ravikel', location:"Oquilla's Eye", region:"Great Ocean", priority:'S+', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', time:'15 min', objective:'Defeat Young Nineshark and return to Ravikel.', bestReward:'Rare sea material option', why:'Important for Carrack progression and future blue gear bottlenecks.', stage:'Do now with Caravel'},
    {id:'young-blackrust', name:"[Daily] Old Moon Guild's Young Black Rust Hunter", reset:'Daily', npc:'Ravikel', location:"Oquilla's Eye", region:"Great Ocean", priority:'S+', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Hard', time:'15-25 min', objective:'Defeat Young Black Rust and return to Ravikel.', bestReward:'Tear of the Ocean / blue flame style rare reward', why:'High-value bottleneck material. Take the rare material over common boxes.', stage:'Do now with Caravel'},
    {id:'precious-coral', name:'[Daily] Precious Coral Piece', reset:'Daily', npc:'Otter Merchants / Oquilla NPC', location:"Oquilla's Eye", region:"Oquilla's Eye", priority:'S', solo:'Solo', ship:'Any ship', difficulty:'Easy', time:'5-10 min', objective:'Gather or exchange Iridescent Coral Pieces around Oquilla.', bestReward:'Seaweed Stalk / material exchange', why:'Fast daily source of Carrack material support items.', stage:'Do now with Caravel'},
    {id:'young-otter', name:'[Daily] For the Young Otter Merchants', reset:'Daily', npc:'Curio', location:"Oquilla's Eye", region:"Oquilla's Eye", priority:'S', solo:'Solo', ship:'Any ship', difficulty:'Easy', time:'5 min', objective:'Complete the Otter merchant request at Oquilla.', bestReward:"Cox Pirates' Artifact / sea material", why:'Quick daily. Useful for ship upgrade material stock.', stage:'Do now with Caravel'},
    {id:'guild-charity', name:'[Daily] Our Guild is not a Charity Group', reset:'Daily', npc:'Ravikel / Old Moon Guild', location:"Oquilla's Eye", region:"Oquilla's Eye", priority:'S', solo:'Solo', ship:'Caravel+', difficulty:'Easy', time:'5-10 min', objective:'Complete the delivery/collection task requested by the Old Moon Guild.', bestReward:'Cobalt Ingot / ship material', why:'Excellent low-effort daily for Carrack materials.', stage:'Do now with Caravel'},
    {id:'serendian-soldiers', name:'[Daily] For the Serendian Soldiers', reset:'Daily', npc:'Soldier', location:"Oquilla's Eye", region:"Oquilla's Eye", priority:'A', solo:'Solo', ship:'Any ship', difficulty:'Easy', time:'5 min', objective:'Bring supplies or complete the soldier request.', bestReward:'Sailing EXP / material reward', why:'Good filler daily if you are already at Oquilla.', stage:'Do if nearby'},
    {id:'croix-hekaru', name:'[Daily] Wanted: Hekaru', reset:'Daily', npc:'Croix', location:'Velia Wharf', region:'Velia', priority:'A', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', time:'10-15 min', objective:'Defeat Hekaru for Croix.', bestReward:'Sailing EXP + Origin of Wind', why:'Good Sailing EXP and combat practice, but less important than Oquilla core dailies.', stage:'Do if time'},
    {id:'croix-oceanstalker', name:'[Daily] Wanted: Ocean Stalker', reset:'Daily', npc:'Croix', location:'Velia Wharf', region:'Velia', priority:'A', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', time:'10-15 min', objective:'Defeat Ocean Stalker for Croix.', bestReward:'Sailing EXP + Origin of Wind', why:'Useful daily if you want Sailing EXP.', stage:'Do if time'},
    {id:'dius-treasure', name:'[Daily] A Treasure Swimming in the Ocean', reset:'Daily', npc:'Dius', location:'Port Epheria', region:'Port Epheria', priority:'B', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', time:'10-15 min', objective:'Complete Dius sea monster request.', bestReward:'Sailing EXP / Origin of Wind', why:'Optional because Port Epheria route can waste time unless already nearby.', stage:'Optional'},
    {id:'tinberra-delivery', name:'[Daily] Tinberra Island Delivery', reset:'Daily', npc:'Island Trade/Barter NPC', location:'Tinberra Island', region:'Sea Islands', priority:'A', solo:'Solo', ship:'Caravel', difficulty:'Easy', time:'10-20 min', objective:'Deliver requested barter/supply item.', bestReward:'Crow Coins / barter support reward', why:'Good when combined with barter routes.', stage:'Do while bartering'},
    {id:'hakoven-delivery', name:'[Daily] Hakoven Delivery', reset:'Daily', npc:'Island Trade/Barter NPC', location:'Hakoven Island', region:'Margoria route', priority:'B', solo:'Solo', ship:'Caravel', difficulty:'Easy', time:'20-30 min', objective:'Deliver requested goods.', bestReward:'Crow Coins', why:'Long trip. Do only if route lines up with your barter refresh.', stage:'Optional'},
    {id:'candidum-weekly', name:"[Weekly] Old Moon Guild's Candidum Hunter", reset:'Weekly', npc:'Ravikel', location:"Oquilla's Eye", region:'Great Ocean', priority:'S+', solo:'Solo Recommended', ship:'Caravel+ / Carrack faster', difficulty:'Hard', time:'20-30 min', objective:'Defeat Candidum and collect specimen.', bestReward:'Crow Coin Bundle / rare material', why:'Never skip. Best long-term value for Carrack Advance and blue gear.', stage:'Do weekly'},
    {id:'nineshark-weekly', name:"[Weekly] Old Moon Guild's Nineshark Hunter", reset:'Weekly', npc:'Ravikel', location:"Oquilla's Eye", region:'Great Ocean', priority:'S+', solo:'Solo Recommended', ship:'Caravel+ / Carrack faster', difficulty:'Hard', time:'20-30 min', objective:'Defeat Nineshark and return to Ravikel.', bestReward:'Crow Coin Bundle / rare material', why:'Never skip. Excellent weekly sea progression value.', stage:'Do weekly'},
    {id:'blackrust-weekly', name:"[Weekly] Old Moon Guild's Black Rust Hunter", reset:'Weekly', npc:'Ravikel', location:"Oquilla's Eye", region:'Great Ocean', priority:'S+', solo:'Party Optional', ship:'Strong Caravel / Carrack', difficulty:'Very Hard', time:'25-40 min', objective:'Defeat Black Rust and collect specimen.', bestReward:'Tear/blue-flame style rare material or Crow Coin Bundle', why:'Major bottleneck. Party is faster if your Caravel gear is still weak.', stage:'Do weekly'},
    {id:'croc-weekly', name:'[Weekly] Saltwater Crocodile Hunter', reset:'Weekly', npc:'Oquilla / Great Ocean NPC', location:'Great Ocean', region:'Great Ocean', priority:'S', solo:'Party Optional', ship:'Strong Caravel+ / Carrack', difficulty:'Very Hard', time:'30+ min', objective:'Defeat Saltwater Crocodiles.', bestReward:'Rare sea material', why:'High-value but harder. Do after core Ravikel weeklies.', stage:'Do weekly if able'},
    {id:'lekrashan-weekly', name:'[Weekly] Lekrashan Hunt', reset:'Weekly', npc:'Sailing quest NPC', location:'Margoria / Great Ocean', region:'Great Ocean', priority:'S', solo:'Party Optional', ship:'Carrack recommended', difficulty:'Very Hard', time:'30+ min', objective:'Defeat Lekrashan.', bestReward:'Rare sea material / coins', why:'Great reward but better after Carrack or with group.', stage:'Skip until Carrack unless carried'},
    {id:'khan-weekly', name:'Khan Guild Raid', reset:'Weekly', npc:'Guild / Khan summon', location:"Oquilla's Eye", region:"Oquilla's Eye", priority:'S', solo:'Guild Required', ship:'Guild content', difficulty:'Very Hard', time:'30+ min', objective:'Join guild Khan raid.', bestReward:"Khan's Scale / guild reward", why:'Important for ship materials and alchemy stone path, but requires guild.', stage:'Guild content'},
    {id:'barter-refresh', name:'Barter Refresh Routine', reset:'Repeatable', npc:'Barter UI / Island NPCs', location:'Sea routes', region:'All seas', priority:'S+', solo:'Solo', ship:'Caravel', difficulty:'Easy', time:'Variable', objective:'Use your barter refreshes and focus on material/crow coin routes.', bestReward:'Crow Coins + Carrack materials', why:'Your Carrack Advance progress depends heavily on barter count, coins, and brilliant mats.', stage:'Do every session'}
  ],
  materials: [
    {id:'brilliant-rock-salt-ingot', name:'Brilliant Rock Salt Ingot', need:35, have:0, source:'High-level barter chains, Crow Coin shop backup', priority:'S+', note:'One of the main Advance bottlenecks.'},
    {id:'brilliant-pearl-shard', name:'Brilliant Pearl Shard', need:35, have:0, source:'High-level barter chains, Crow Coin shop backup', priority:'S+', note:'Advance bottleneck. Track every shard.'},
    {id:'deep-tide-timber', name:'Deep Tide-Dyed Standardized Timber Square', need:100, have:0, source:'Oquilla dailies, barter, Crow Coin shop', priority:'S+', note:'Core Carrack upgrade material.'},
    {id:'moon-scale-plywood', name:'Moon Scale Plywood', need:100, have:0, source:'Young Candidum daily, Khan Scale processing, Crow Coin shop', priority:'S+', note:'Keep doing the relevant dailies.'},
    {id:'tide-dyed-silk', name:'Tide-Dyed Standardized Timber / Silk Materials', need:100, have:0, source:'Barter and Oquilla quests', priority:'S', note:'Commonly blocks progress if ignored.'},
    {id:'tear-ocean', name:'Tear of the Ocean', need:42, have:0, source:'Black Rust related quests / rare rewards', priority:'S+', note:'Rare; prioritize when offered as reward.'},
    {id:'cobalt-ingot', name:'Cobalt Ingot', need:30, have:0, source:'Our Guild is not a Charity Group, barter, Crow Coin shop', priority:'S', note:'Fast daily source exists.'},
    {id:'seaweed-stalk', name:'Seaweed Stalk', need:125, have:0, source:'Precious Coral Piece, otter exchange, Crow Coin shop', priority:'S', note:'Do daily if short.'},
    {id:'cox-parley', name:"Cox Pirates' Artifact (Parley Expert)", need:30, have:0, source:'Oquilla quests, otter merchants, Crow Coins', priority:'A', note:'Needed on the broader upgrade path.'},
    {id:'cox-combat', name:"Cox Pirates' Artifact (Combat)", need:60, have:0, source:'Sea monster drops and sailing quests', priority:'A', note:'Collect while doing combat dailies.'}
  ],
  shipParts: [
    {part:'Caravel gear to +10', items:['Epheria Caravel: Brass Prow +10','Epheria Caravel: Upgraded Plating +10','Epheria Caravel: Mayna Cannon +10','Epheria Caravel: Stratus Wind Sail +10'], note:'Required before upgrading the Caravel into Carrack Advance.'},
    {part:'Carrack Advance Green Gear', items:['Toro Cannon','Toro Sail','Toro Prow','Toro Plating'], note:'Bought with Crow Coins after Carrack. Good first gear target.'},
    {part:'Carrack Advance Blue Gear', items:['Advanced Chiro Cannon','Advanced Chiro Sail','Advanced Chiro Prow','Advanced Chiro Plating'], note:'Endgame long-term goal. Start saving materials now.'}
  ],
  monsters: [
    {name:'Young Candidum', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', drops:'Moon Scale Plywood path, Oquilla coin/naval fame rewards', tip:'Circle, fire volleys, repair early.'},
    {name:'Young Nineshark', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Medium', drops:'Sea materials and quest completion rewards', tip:'Avoid staying still; turn before it charges.'},
    {name:'Young Black Rust', solo:'Solo Recommended', ship:'Caravel+', difficulty:'Hard', drops:'Rare Black Rust quest rewards', tip:'Bring many Ship Repair Materials.'},
    {name:'Candidum', solo:'Solo Recommended', ship:'Strong Caravel / Carrack', difficulty:'Hard', drops:'Weekly specimen, sea mats', tip:'Soloable but slow with weak Caravel gear.'},
    {name:'Nineshark', solo:'Solo Recommended', ship:'Strong Caravel / Carrack', difficulty:'Hard', drops:'Weekly specimen, sea mats', tip:'Carrack makes this much smoother.'},
    {name:'Black Rust', solo:'Party Optional', ship:'Strong Caravel / Carrack', difficulty:'Very Hard', drops:'Rare weekly rewards', tip:'Party recommended until your ship is strong.'},
    {name:'Saltwater Crocodile', solo:'Party Optional', ship:'Carrack recommended', difficulty:'Very Hard', drops:'Rare sea materials', tip:'Do with group or after Carrack.'},
    {name:'Lekrashan', solo:'Party Optional', ship:'Carrack recommended', difficulty:'Very Hard', drops:'Endgame sea rewards', tip:'Skip until Carrack unless joining group.'}
  ],
  sailors: [
    {name:'Innocent Goblin Sailor', best:'Speed / Bartering', rating:'S', note:'Great for movement and daily routes.'},
    {name:'Realistic Goblin Sailor', best:'Speed balance', rating:'A', note:'Useful if you cannot find perfect Innocent.'},
    {name:'Innocent Giant Sailor', best:'Weight / Bartering', rating:'A', note:'Good for Caravel cargo runs.'},
    {name:'Human Sailor', best:'Balanced', rating:'B', note:'Fine early, replace later.'},
    {name:'Dwarf Sailor', best:'Durability / support', rating:'B', note:'Situational.'},
    {name:'Giant Sailor', best:'Cargo / stability', rating:'B', note:'Works for heavy routes.'}
  ]
};
